AllCops:
  Exclude:
    - config/initializers/devise.rb
    - bin/*
    - Gemfile
    - db/schema.rb
    - db/migrate/*

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/AbcSize:
  Max: 17

Metrics/BlockLength:
  Max: 35